version: '3.3'
services:
  jupyter_notebook:
    restart: always
    image: 'jupyter-notebook:bdmti'
    build:
      context: '.'
      dockerfile: dockerfile
      environment:
            JUPYTERPASSWORD: $JUPYTERPASSWORD
      cache_from:
        - 'jupyter-notebook:bdmti'
    volumes: 
      - './code/:/home/jupyter/code/'
    ports:
      - '8888:8888'
