version: '3.3'
services:
  jupyter_notebook:
    build:
      context: '.'
      dockerfile: dockerfile
      cache_from:
        - 'Jupyter-Notebook:BDMTI'
    volumes: 
      - './code/:/code/'
    ports:
      - '8080:8080'
