version: '3.3'
services:
  jupyter_notebook:
    restart: always
    image: 'jupyter-notebook:latest'
    build:
      context: '.'
      dockerfile: dockerfile
      cache_from:
        - 'jupyter-notebook:latest'
    volumes: 
      - '/root/jupyter_notebook/:/home/jupyter/code/'
    entrypoint: ['jupyter','notebook','--no-browser',"--ip='*'","--NotebookApp.token='$JUPYTERPASSWORD'","--NotebookApp.password=$JUPYTERPASSWORD"]
networks:
  main:
    external:
      name : main-overlay
