version: '3.3'
services:
  jupyter_notebook:
    restart: always
    networks:
      main:
          ipv4_address: 10.0.2.21
    image: 'jupyter-notebook:latest'
    build:
      context: '.'
      dockerfile: dockerfile
      cache_from:
        - 'jupyter-notebook:latest'
    volumes: 
      - type: volume
        source: jupyter
        target: /home/jupyter/code/
    entrypoint: ['jupyter','notebook','--no-browser',"--ip='*'","--NotebookApp.token='$JUPYTERPASSWORD'","--NotebookApp.password=$JUPYTERPASSWORD"]
networks:
  main:
    external:
      name : main-overlay
volumes:
  jupyter: